# Generated by Django 4.0.3 on 2022-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flightdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fnumber', models.IntegerField(max_length=300, unique=True)),
                ('coname', models.TextField()),
                ('fromdestination', models.TextField()),
                ('todestination', models.TextField()),
                ('nooftickets', models.IntegerField()),
            ],
        ),
    ]
