# Generated by Django 4.0.3 on 2022-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='Fnumber',
            field=models.IntegerField(unique=True),
        ),
    ]
