# Generated by Django 4.0.3 on 2022-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_flightdetails_fnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('User_Id', models.CharField(max_length=20, unique=True)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
