# Generated by Django 4.0.3 on 2022-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_leave_leaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('cost', models.IntegerField()),
                ('airlineName', models.TextField()),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
            ],
        ),
    ]
