# Generated by Django 4.0.3 on 2022-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_flights'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='flight_adate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='flight_ddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='flight_fare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
