# Generated by Django 4.0.3 on 2022-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_flights_flightdetails_flight_adate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='Fnumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
