# Generated by Django 4.0.3 on 2022-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_flightdetails_fnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetails',
            name='flight_adate',
        ),
        migrations.RemoveField(
            model_name='flightdetails',
            name='flight_ddate',
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='arrivalTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='boardingTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
