# Generated by Django 3.1.2 on 2022-04-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_flightdetails_flight_adate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_on_Card', models.TextField()),
                ('CardNumber', models.IntegerField(unique=True)),
                ('ExpDate', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketNumber', models.CharField(max_length=9)),
                ('FlightNumber', models.CharField(max_length=6)),
                ('FlightDate', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Status', models.CharField(max_length=20)),
                ('BookingDate', models.CharField(max_length=15)),
                ('BookingTime', models.CharField(max_length=10)),
                ('FlightBoarding', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('PassDet', models.IntegerField()),
                ('FlightName', models.CharField(max_length=20)),
                ('FlightArrival', models.CharField(max_length=10)),
                ('FlightFrom', models.CharField(max_length=20)),
                ('FlightTo', models.CharField(max_length=20)),
                ('FlightFare', models.FloatField()),
                ('FlightCharges', models.FloatField()),
                ('TotalFare', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
