# Generated by Django 3.1.2 on 2022-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20220426_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passengers', models.TextField()),
                ('TicketNumber', models.CharField(max_length=9)),
                ('FlightNumber', models.CharField(max_length=6)),
                ('FlightDate', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Status', models.CharField(max_length=20)),
                ('BookingDate', models.CharField(max_length=15)),
                ('BookingTime', models.CharField(max_length=10)),
                ('FlightBoarding', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('FlightName', models.CharField(max_length=20)),
                ('FlightArrival', models.CharField(max_length=10)),
                ('FlightFrom', models.CharField(max_length=20)),
                ('FlightTo', models.CharField(max_length=20)),
                ('FlightFare', models.FloatField()),
                ('FlightCharges', models.FloatField()),
                ('TotalFare', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TicketDetails',
        ),
    ]
