# Generated by Django 3.1.2 on 2022-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_ticket_details_passengercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_details',
            name='TicketNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
