# Generated by Django 4.0.2 on 2022-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_discount_alter_flightdetails_id_alter_leaves_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Offer_Ammount',
            field=models.CharField(max_length=20),
        ),
    ]
