# Generated by Django 4.0.2 on 2022-05-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_discount_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Offer_Ammount',
            field=models.FloatField(max_length=20),
        ),
    ]
