# Generated by Django 4.0.2 on 2022-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_discount_offer_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_details',
            name='DiscountAmount',
            field=models.CharField(default=100, max_length=15),
            preserve_default=False,
        ),
    ]
